version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    working_directory: ~/repo
    docker:
      - image: circleci/python:3.9.0b5
        auth:
          username: jurezic
          password: S37aXzdYXUagqDS
    steps:
      - checkout
      - run:
         name: run Unit tests
         command: pip install pytest
      - python/load-cache
      - python/install-deps
      - python/save-cache

workflows:
  main:
    jobs:
      - build-and-test
